#cloud-config
package_update: true
package_upgrade: false
hostname: worker-1

write_files:
  - path: /etc/rancher/k3s-agent.env
    permissions: '0644'
    content: |
      K3S_URL="https://10.0.0.2:6443"
      K3S_TOKEN="my-super-secure-token"
      INSTALL_K3S_EXEC="--flannel-iface=enp7s0 --kubelet-arg cloud-provider=external --node-label role=worker --node-name=worker-1"

runcmd:
  - |
    echo "[cloudinit] Waiting for K3s master to become reachable..."
    retries=5
    count=0
    until curl -k --silent --fail "https://10.0.0.2:6443/ping"; do
      count=$((count + 1))
      if [ "$count" -ge "$retries" ]; then
        echo "[cloudinit] K3s master not reachable after $retries attempts, exiting."
        exit 1
      fi
      echo "[cloudinit] Attempt $count of $retries failed. Retrying in 5s..."
      sleep 5
    done
    echo "[cloudinit] K3s master is ready!"

  - |
    echo "[cloudinit] Installing K3s agent..."
    curl -sfL https://get.k3s.io | \
      INSTALL_K3S_SKIP_START=true sh -s - agent --env-file /etc/rancher/k3s-agent.env 2>&1 | tee /var/log/k3s-agent-install.log

  - |
    echo "[cloudinit] Starting K3s agent..."
    systemctl enable k3s-agent
    systemctl start k3s-agent
