- name: Generate K3s token if not provided
  ansible.builtin.set_fact:
    k3s_token: "{{ lookup('password', '/dev/null length=16 chars=hex') }}"
  when: k3s_token is not defined

- name: Include controller tasks
  ansible.builtin.include_tasks: install_controller.yaml