---
- name: Set up Kubernetes cluster with K3s and Flux
  hosts: controller
  become: true
  roles:
    - k3s


- name: Setup Flux Cluster on a singular controller
  hosts: flux_controller
  become: true
  roles:
    - flux:
      github_owner: MarcHoog
      github_repo: MyKubernetes
      github_path: "myclusters/schiphol"


#- name: Join agent nodes to the cluster
#  hosts: agent
#  become: true
#  tasks:
#    - name: Retrieve K3s token from master
#      ansible.builtin.fetch:
#        src: /var/lib/rancher/k3s/server/node-token
#        dest: /tmp/k3s_token
#        flat: yes
#      delegate_to: "{{ groups['k3s_master'][0] }}"

#    - name: Install K3s agent
#      ansible.builtin.include_tasks: install_agent.yml
