apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    server:
      ha:
        enabled: false
      dataStorage:
        enabled: true
        size: 1Gi
        storageClass: "local-path"
      standalone:
        enabled: true
    ui:
      enabled: true
