
- name: Check if K3s is installed
  ansible.builtin.stat:
    path: /usr/local/bin/flux
  register: flux_bin

- name: Install flux CLI (simplified)
  ansible.builtin.shell: |
    curl -s https://fluxcd.io/install.sh | sudo bash
  when: not flux_bin.stat.exists

- name: Bootstrap Flux to local cluster with generated manifests
  register: flux_bootstrap
  ansible.builtin.script: bootstrap_flux.sh
  environment:
    KUBECONFIG: 
    GITHUB_TOKEN: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    GH_USERNAME: {{ github_owner }}
    GH_REPOSITORY: {{ github_repo }}
    GH_BRANCH: {{ github_branch }}
    GH_PATH: {{ github_path }}