name: Schiphol | Run Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      create_snapshots:
        description: "Create Hetzner snapshots before destroy?"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"
permissions:
  id-token: write
  contents: read
jobs:
  call-terraform-destroy:
    uses: marchoog/devops/.github/workflows/hetzner_template_tf_destroy.yml@main
    with:
      tf_key: "tfstate/hetzner/schiphol"
      tf_storage_account: saiaceun
      tf_container_name: tf-state
      working_directory: "tf-environments/schiphol"
      environment: prod

    secrets:
      TF_GITHUB_TOKEN_PAT: ${{ secrets.TF_GITHUB_TOKEN_PAT }}
      AZURE_CLIENT_ID: ${{ secrets.TF_AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.TF_AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.TF_AZURE_SUBSCRIPTION_ID }}
      TF_HETZNER_TOKEN: ${{ secrets.TF_HETZNER_TOKEN }}
