name: Schiphol | Terraform Plan on PR

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - "terraform/schiphol/**"

jobs:
  call-terraform-plan:
    uses: marchoog/devops/.github/workflows/hetzner_template_tf_plan.yml@main
    with:
      tf_key: "tfstate/hetzner/schiphol"
      tf_storage_account: saiaceun
      tf_container_name: tf-state
      working_directory: "tf-environments/schiphol"
      environment: prod
    secrets:
      TF_GITHUB_TOKEN_PAT: ${{ secrets.TF_GITHUB_TOKEN_PAT }}
      AZURE_CLIENT_ID: ${{ secrets.TF_AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.TF_AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.TF_AZURE_SUBSCRIPTION_ID }}
      TF_HETZNER_TOKEN: ${{ secrets.TF_HETZNER_TOKEN }}
