name: Hetzner Schiphol | Run Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      create_snapshots:
        description: 'Create Hetzner snapshots before destroy?'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  call-terraform-destroy:
    uses: marchoog/devops/.github/workflows/template_tf_destroy.yml@main
    with:
      create_snapshots: ${{ github.event.inputs.create_snapshots }}
      working_directory: 'terraform/env/schiphol'
    secrets:
      TF_GITHUB_TOKEN_PAT: ${{ secrets.TF_GITHUB_TOKEN_PAT }}
      TF_AWS_ACCES_KEY_ID: ${{ secrets.TF_AWS_ACCES_KEY_ID }}
      TF_AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      TF_HETZNER_TOKEN: ${{ secrets.TF_HETZNER_TOKEN }}
