name: Hetzner Schiphol | Terraform Validate on Push

on:
  push:
    branches:
      - '**'
    paths:
      - 'terraform/env/schiphol/**'

jobs:
  call-terraform-validate:
    uses: marchoog/devops/.github/workflows/template_tf_validate.yml@main
    with:
      working_directory: "./terraform/env/schiphol"
    secrets:
      TF_GITHUB_TOKEN_PAT: ${{ secrets.SCHIPHOL_GITHUB_TOKEN_PAT }}
      TF_AWS_ACCES_KEY_ID: ${{ secrets.SCHIPHOL_AWS_ACCES_KEY_ID }}
      TF_AWS_SECRET_ACCESS_KEY: ${{ secrets.SCHIPHOL_AWS_SECRET_ACCESS_KEY }}