name: Schiphol | Terraform Validate on Push

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "terraform/env/hetzner/schiphol/**"

jobs:
  call-terraform-validate:
    uses: marchoog/devops/.github/workflows/hetzner_template_tf_validate.yml@main
    with:
      tf_key: "tfstate/hetzner/schiphol"
      tf_storage_account: saiaceun
      tf_container_name: tf-state
      working_directory: "terraform/schiphol"
    secrets:
      TF_GITHUB_TOKEN_PAT: ${{ secrets.TF_GITHUB_TOKEN_PAT }}
      AZURE_CLIENT_ID: ${{ secrets.TF_AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.TF_AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.TF_AZURE_SUBSCRIPTION_ID }}
      TF_AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
