name: Babilon | Terraform Plan on PR

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - "terraform/env/hetzner/babilon/**"

jobs:
  call-terraform-plan:
    uses: marchoog/devops/.github/workflows/hetzner_template_tf_plan.yml@main
    with:
      tf_key: "tfstate/babilon"
      working_directory: "terraform/env/hetzner/babilon"
    secrets:
      TF_GITHUB_TOKEN_PAT: ${{ secrets.TF_GITHUB_TOKEN_PAT }}
      TF_AWS_ACCES_KEY_ID: ${{ secrets.TF_AWS_ACCES_KEY_ID }}
      TF_AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      TF_HETZNER_TOKEN: ${{ secrets.TF_HETZNER_BABILON_TOKEN }}
