name: Terraform Destroy Template

on:
  workflow_call:
    inputs:
      create_snapshots:
        required: true
        type: string
        description: "Create Hetzner snapshots before destroy?"
      working_directory:
        required: true
        type: string
        description: "Terraform working directory"
      tf_key:
        required: true
        type: string
        description: "Remote state key (path) in the Azure Storage container"
      tf_storage_account:
        required: true
        type: string
        description: "Azure Storage Account used for TF state backend"
      tf_container_name:
        required: true
        type: string
        description: "Azure Storage container used for TF state backend"
      tf_version:
        required: false
        type: string
        default: "1.11.4"
      environment:
        required: true
        type: string
    secrets:
      TF_GITHUB_TOKEN_PAT:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      TF_HETZNER_TOKEN:
        required: true

jobs:
  hetzner-snapshots:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - if: ${{ inputs.create_snapshots == 'yes' }}
        name: Checkout repository
        uses: actions/checkout@v4

      - if: ${{ inputs.create_snapshots == 'yes' }}
        name: Install Hcloud CLI
        run: |
          curl -sSL https://github.com/hetznercloud/cli/releases/latest/download/hcloud-linux-amd64.tar.gz | tar -xz
          sudo mv hcloud /usr/local/bin/hcloud
          hcloud version

      - if: ${{ inputs.create_snapshots == 'yes' }}
        name: Create Hetzner Snapshots
        env:
          HCLOUD_TOKEN: ${{ secrets.TF_HETZNER_TOKEN }}
        run: python3 create_hetzner_snapshot.py

  terraform-destroy:
    environment: ${{ inputs.environment }}
    needs: hetzner-snapshots
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Hcloud CLI
        run: |
          curl -sSL https://github.com/hetznercloud/cli/releases/latest/download/hcloud-linux-amd64.tar.gz | tar -xz
          sudo mv hcloud /usr/local/bin/hcloud
          hcloud version

      - name: Terraform Setup (Azure)
        uses: ./.github/actions/azure-terraform-setup
        with:
          tf_version: ${{ inputs.tf_version }}
          github_token_pat: ${{ secrets.TF_GITHUB_TOKEN_PAT }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tf_storage_account: ${{ inputs.tf_storage_account }}
          tf_container_name: ${{ inputs.tf_container_name }}
          tf_key: ${{ inputs.tf_key }}
          working_directory: ${{ inputs.working_directory }}

      - name: Terraform Destroy
        env:
          HCLOUD_TOKEN: ${{ secrets.TF_HETZNER_TOKEN }}
        run: terraform destroy -auto-approve -input=false
