name: Terraform Destroy Template

on:
  workflow_call:
    inputs:
      create_snapshots:
        required: true
        type: string
        description: 'Create Hetzner snapshots before destroy?'
      working_directory:
        required: true
        type: string
        description: 'Working directory for terraform commands'
    secrets:
      TF_GITHUB_TOKEN_PAT:
        required: true
      TF_AWS_ACCES_KEY_ID:
        required: true
      TF_AWS_SECRET_ACCESS_KEY:
        required: true
      TF_HETZNER_TOKEN:
        required: true

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Hcloud CLI
        run: |
          curl -sSL https://github.com/hetznercloud/cli/releases/latest/download/hcloud-linux-amd64.tar.gz | tar -xz
          sudo mv hcloud /usr/local/bin/hcloud
          hcloud version

      - name: Create Hetzner Snapshots
        if: ${{ inputs.create_snapshots == 'yes' }}
        env:
          HCLOUD_TOKEN: ${{ secrets.TF_HETZNER_TOKEN }}
        run: |
          for server_info in $(hcloud server list -o noheader -o columns=id,name); do
            id=$(echo $server_info | awk '{print $1}')
            name=$(echo $server_info | awk '{print $2}')
            description="vm-snapshot-$name"
            echo "Creating snapshot for server $id with description: $description"
            hcloud server create-image $id --description "$description"
          done

      - name: Terraform Setup
        uses: ./.github/actions/terraform-setup
        with:
          tf_version: ${{ env.TF_VERSION }}
          github_token_pat: ${{ secrets.TF_GITHUB_TOKEN_PAT }}
          aws_access_key_id: ${{ secrets.TF_AWS_ACCES_KEY_ID }}
          aws_secret_access_key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCES_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
          HCLOUD_TOKEN: ${{ secrets.TF_HETZNER_TOKEN }}
        run: terraform destroy -auto-approve -input=false
